export const TOUR_TYPES = [
  "Adventure",
  "Cultural",
  "Historical",
  "Nature",
  "Religious",
  "Beach",
  "Mountain",
  "Wildlife",
  "Photography",
  "Food & Culinary",
  "Shopping",
  "Relaxation",
  "Educational",
  "Family",
  "Luxury",
  "Budget",
  "Group",
  "Private",
  "Day Trip",
  "Multi-day",
  "International",
  "Domestic",
  "City Tour",
  "Rural Tour",
  "Heritage",
  "Spiritual",
  "Wellness",
  "Sports",
  "Music & Arts",
  "Festival",
];

export const INCLUSIVE_FEATURES = [
  "Accommodation",
  "Meals (Breakfast)",
  "Meals (Lunch)",
  "Meals (Dinner)",
  "All Meals",
  "Transportation",
  "Airport Transfer",
  "Local Transport",
  "Guide Services",
  "Entrance Fees",
  "Activities",
  "Equipment Rental",
  "Insurance",
  "Visa Assistance",
  "Flight Tickets",
  "Train Tickets",
  "Bus Tickets",
  "Boat Transfer",
  "Welcome Drink",
  "Snacks",
  "Water Bottles",
  "WiFi",
  "Air Conditioning",
  "Room Service",
  "Laundry Service",
  "Spa Access",
  "Pool Access",
  "Gym Access",
  "Parking",
  "Pickup & Drop",
];

export const TOUR_HIGHLIGHTS = [
  "Scenic Views",
  "Historical Monuments",
  "Cultural Experience",
  "Adventure Activities",
  "Wildlife Safari",
  "Local Cuisine",
  "Shopping Experience",
  "Photography Opportunities",
  "Relaxation & Wellness",
  "Educational Tours",
  "Festival Celebrations",
  "Sunset/Sunrise Views",
  "Mountain Trekking",
  "Beach Activities",
  "River Rafting",
  "Camping Experience",
  "Local Art & Crafts",
  "Traditional Music",
  "Temple Visits",
  "Nature Walks",
  "Bird Watching",
  "Stargazing",
  "Local Markets",
  "Traditional Dance",
  "Cooking Classes",
  "Yoga Sessions",
  "Meditation Retreat",
  "Heritage Sites",
  "National Parks",
  "Waterfalls",
];

export const SPECIAL_REQUIREMENTS = [
  "Visa Required",
  "Passport Required",
  "Vaccination Required",
  "Medical Certificate",
  "Travel Insurance",
  "Special Dietary Needs",
  "Wheelchair Accessible",
  "Child Friendly",
  "Senior Citizen Friendly",
  "Pet Friendly",
  "Smoking Not Allowed",
  "Alcohol Not Allowed",
  "Dress Code Required",
  "Modest Clothing",
  "Comfortable Shoes",
  "Swimming Gear",
  "Hiking Equipment",
  "Camera Equipment",
  "Power Bank Required",
  "Local SIM Card",
  "Cash Preferred",
  "Credit Card Accepted",
  "Mobile App Required",
  "Guide Required",
  "Group Size Limit",
  "Age Restrictions",
  "Fitness Level Required",
  "Altitude Sickness Warning",
  "Weather Dependent",
  "Seasonal Availability",
];

export const EXCLUSIVE_FEATURES = [
  "Premium Accommodation",
  "Private Guide",
  "VIP Transportation",
  "Exclusive Access",
  "Priority Booking",
  "Custom Itinerary",
  "Luxury Amenities",
  "Private Dining",
  "Spa Services",
  "Butler Service",
  "Helicopter Transfer",
  "Private Beach Access",
  "Exclusive Events",
  "Personal Photographer",
  "Customized Meals",
  "Premium Seating",
  "Fast Track Entry",
  "Private Viewing",
  "Exclusive Workshops",
  "Luxury Transportation",
  "Premium Equipment",
  "Private Tours",
  "Exclusive Locations",
  "VIP Treatment",
  "Custom Experiences",
  "Premium Services",
  "Exclusive Packages",
  "Luxury Accommodation",
  "Private Experiences",
  "Premium Support",
];
